scene:
  scene_path: "/root/projects/semantic-gaussians/dataset/mipnerf360/garden"
  dataset_name: "mipnerf360"
  test_cameras: False
  colmap_images: "images_4"
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: False
  device: "cuda:0"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 0

model:
  sh_degree: 3
  model_dir: "./output/garden_replication"
  dynamic: False
  load_iteration: -1
  device: "cuda:0"

render:
  fusion_dir: "./output/garden_replication/0.pt"
  model_2d: samclip # choose from openseg, lseg, samclip, vlpart
